import reactHelper from 'react-helper';
import MenuApp from './components/menu/index.jsx';
import HeroApp from './components/hero/index.jsx';
import SearchApp from './components/search/index.jsx';
import ArtworkApp from './components/artwork/index.jsx';
import CampusApp from './components/campus/index.jsx';
import FacilitiesApp from './components/facilities/index.jsx';
import AlumniApp from './components/alumni/index.jsx';
import CoursesApp from './components/courses/index.jsx';
import DiscoverApp from './components/discover/index.jsx';
import AboutApp from './components/about/index.jsx';

reactHelper.register({ MenuApp });
reactHelper.register({ HeroApp });
reactHelper.register({ SearchApp });
reactHelper.register({ ArtworkApp });
reactHelper.register({ CampusApp });
reactHelper.register({ FacilitiesApp });
reactHelper.register({ AlumniApp });
reactHelper.register({ CoursesApp });
reactHelper.register({ DiscoverApp });
reactHelper.register({ AboutApp });
